### ISSUE TITLE
Bazarr release pipeline now create bazarr.zip asset

### ISSUE THREAD

**Issue by morpheus65535** [hotio/bazarr#15]
From now on, for both dev and master branch, we create a bazarr.zip file on each release/pre-release. It can be downloaded using the following URL (for example): https://github.com/morpheus65535/bazarr/releases/download/v0.9.4/bazarr.zip

Could you update all your images to use it?

Starting with 0.9.5 final, you wont get the required files for Bazarr to start from tarball. 

Thanks!

**Comment by mrhotio** [comment]
...done! Sorry it took a few days.

**Comment by morpheus65535** [comment]
np, thanks!
